### ISSUE TITLE
fset:position returns position relative to :start keyword parameter

### ISSUE THREAD

**Issue by henkvr** [slburson/fset#11]
Personally, I'd much prefer absolute position, for consistency both with cl:position and across fset:position's methods.

(fset:position #+ (fset:convert 'fset:seq "---+---+---") :start 4)
=> 3
(fset:position #+ "---+---+---" :start 4)
=> 7

**Comment by slburson** [comment]
Agreed -- this is a quite unintentional bug.

**Comment by slburson** [comment]
This is now fixed.  Sorry for the long delay.
