### ISSUE TITLE
Support for named-readtables?

### ISSUE THREAD

**Issue by brianqq** [slburson/fset#14]
It gets pretty hard to use multiple libraries that extend the readtable without using named-readtables. I will be writing up a named-readtable for fset anyway. I can submit a pull request if that is something people would be interested in.

**Comment by brianqq** [comment]
Here is the necessary code (assuming named-readtable is ASDF'd or QL:QUICKLOADed

    (named-readtables:defreadtable syntax
        (:merge nil)
        (:dispatch-macro-char #\# #\{ #'|#{-reader| )
        (:macro-char #\} (get-macro-character #\)) nil )
        (:dispatch-macro-char #\# #\[ #'|#[-reader| )
        (:macro-char #\] (get-macro-character #\)) nil )
        (:dispatch-macro-char #\# #\~ #'|#~-reader| )
        (:dispatch-macro-char #\# #\$ #'|#$-reader| )
        (:dispatch-macro-char #\# #\% #'|#%-reader| ))

**Comment by slburson** [comment]
Added by pfdietz in 6d2f9de.
