### ISSUE TITLE
count-if and count-if-not return nil

### ISSUE THREAD

**Issue by syll-dev** [slburson/fset#15]
count-if and count-if-not on a set return nil :
`(fset:count-if #'evenp (fset:convert 'fset:set (list 1 2 3)))`
`NIL`

In count-if, "returning" n is done inside do-set (twice).

I think the same problem exists with bags, maps and seqs

**Comment by slburson** [comment]
Whoops!!!  I guess I was in a hurry and didn't test it :-(
Thanks for the report.  Not sure when I'll get to it.

**Comment by slburson** [comment]
Paul Dietz fixed this.
