### ISSUE TITLE
Readme mentions FSet project page on common-lisp.net but it is not available

### ISSUE THREAD

**Issue by tuscland** [slburson/fset#17]
Hi,

The Readme file mentions a page that seems no longer available.
Also content about FSet is a bit spread on several pages (tutorial, FSet-CL page, ...).

I would be happy to add this documentation to the Github's Wiki.
Let me know!

Cam

**Comment by slyrus** [comment]
The common-lisp.net page is available but still seems to reference things like the SVN repo. I assume this is the canonical home for fset now? It would be great if the README, etc... clarified the situation.

**Comment by slburson** [comment]
Fixed recently.  I've moved all the docs to the wiki on gitlab.common-lisp.net.  The README now points to [the correct place](https://gitlab.common-lisp.net/fset/fset/-/wikis/home).
