### ISSUE TITLE
build order issues

### ISSUE THREAD

**Issue by slyrus** [slburson/fset#20]
When asdf:load-ing fset I see the following:

; file: /home/sly/quicklisp/local-projects/fset/Code/fset.lisp
; in: DEFMETHOD FSET::SORT-AND-GROUP (FSET:SEQ T)
;     (FSET:DO-SEQ (FSET::X FSET::SORTED)
;       (IF (OR (FSET:EMPTY? FSET::GROUP)
;               (NOT
;                (IF FSET::KEY
;                    #
;                    #)))
;           (FSET:PUSH-LAST FSET::GROUP FSET::X)
;           (PROGN (FSET:PUSH-LAST FSET::RESULT FSET::GROUP) (SETQ FSET::GROUP #))))
; 
; caught STYLE-WARNING:
;   undefined function: FSET:DO-SEQ

;     (FSET:SEQ)
; 
; caught STYLE-WARNING:
;   undefined function: FSET:SEQ

;     (FUNCALL FSET::KEY FSET::X)
; ==>
;   (SB-C::%FUNCALL (SB-KERNEL:%COERCE-CALLABLE-FOR-CALL FSET::KEY) FSET::X)
; 
; caught WARNING:
;   undefined variable: FSET::X

;     (FSET::X FSET::SORTED)
; 
; caught STYLE-WARNING:
;   undefined function: FSET::X
; 
; compilation unit finished
;   Undefined functions:
;     FSET:DO-SEQ FSET:SEQ FSET::X
;   Undefined variable:
;     FSET::X
;   caught 1 WARNING condition
;   caught 8 STYLE-WARNING conditions

The problem is that the SEQ and DO-SEQ macros aren't yet loaded. There are some order dependencies that make fixing this a little bit tricky but I imagine it's relatively straightforward.

**Comment by slburson** [comment]
This has been fixed, in 46459b8, a692b5c, 69a0d59, and others.
