### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [slburson/fset#55]
Building with SBCL 2.4.6.70-a4f5037f5 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id d590b19b9777424f9f0d06196bf8e5c9e61ca2b4

*fset* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD tid=1120418 "main thread" RUNNING {1000E00003}>: no symbol named "CONSTANT" in "GMAP"

```

*fset/test* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD tid=1120414 "main thread" RUNNING {1000E00003}>: no symbol named "CONSTANT" in "GMAP"

```

[Full log here](http://report.quicklisp.org/2024-07-17/failure-report/fset.html)

**Comment by slburson** [comment]
You will need the latest version of Misc-Extensions, which has been moved to a new URL: https://gitlab.common-lisp.net/misc-extensions/misc-extensions.git

**Comment by mdbergmann** [comment]
I'm wondering if the process for quicklisp (which many are waiting for a new release, last was Oct 2023) could be made easier. If misc-extensions is maintained by you it would be great if you could also make sure that URL changes are maintained at quicklisp.
Or maybe it would be OK even to add misc-extensions as a git submodule as it seems to be just one of three dependencies.
