### ISSUE TITLE
Package error in SBCL port of NV-LENGTH, SB-EXT::ONCE-ONLY package lock error

### ISSUE THREAD

**Issue by markhdavid** [slburson/fset#68]
Compiling Code/port.lisp in SBCL 2.4.11, while compiling Code/port.lisp, you get an error like
```
; compiling file "path/to/Code/port.lisp" (written 13 DEC 2024 08:32:28 PM):
; 
; caught ERROR:
;   READ error during COMPILE-FILE: Lock on package SB-EXT violated when interning ONCE-ONLY while in package FSET.
;   See also:
;     The SBCL Manual, Node "Package Locks"(in form starting at line: 376, column: 0, position: 11710)
```
Evidently, no symbol named "ONCE-ONLY" can be found in the SB-EXT package. The error happens while evaluating the defmacro for NV-LENGTH for the #+sbcl case only.

**Comment by markhdavid** [comment]
There is a symbol named "ONCE-ONLY" in the SB-INT package in SBCL 2.4.11.

**Comment by markhdavid** [comment]
Note the version of fset: "1.3.2" (the version currently used by quicklisp)

**Comment by markhdavid** [comment]
Just noticed this is a duplicate of issue "fix: proper external package for sb-int:once-only #46", which was fixed in the current version of fset: "1.4.0". (It would be nice for quicklisp to use this later version.) Closing as duplicate.

**Comment by slburson** [comment]
@markhdavid Quicklisp is already on 1.4.2, which includes this fix.  I think you need to update your Quicklisp installation.

**Comment by markhdavid** [comment]
> @markhdavid Quicklisp is already on 1.4.2, which includes this fix. I think you need to update your Quicklisp installation.

Think you're right, I'm livin' in the past
